### PR TITLE
fixed : tap to stop flinging not working

### PR DESCRIPTION
**Pull request by Mids**

### CODE REVIEW

**Comment by briangriffey** [comment]
@Mids can you get this merge-ready and I'll merge it.

**Comment by Mids** [comment]
@briangriffey I don't know what you're talking about. Do I have to do something for you to merge it?

**Comment by briangriffey** [comment]
Currently it says that we can't automatically merge it. So you'll probably need to pull from this repo and merge it into yours and then re-push the commit.

**Comment by Mids** [comment]
@briangriffey is this available??
https://github.com/maurycyw/StaggeredGridView/pull/61

**Pull request closed without merging**
